version: "2.1"
# Solr
services:
  solr:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: solr
    hostname: solr
    image: docksal/solr:4.x
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/solr/conf:/var/lib/solr/conf:ro
    
      